#+TITLE: simple image gallery

This script is a static html image gallery generator in scheme. It
takes a folder with images (and/or videos) and generates a html file
with an image gallery. The images are resized and thumbnails are
created. Videos are all converted to webm files. The images are sorted
by their timestamp, where the exif date-time value is used if
available and otherwise the file last modification timestamp.

* Setup

Some external programs are needed:

- [[http://curl.haxx.se/][curl]] (to download all the css and js files)
- convert ([[http://imagemagick.org/][imagemagick]] or [[http://www.graphicsmagick.org/][graphicsmagick]])
- [[http://www.sentex.net/~mwandel/jhead/][jhead]]
- [[http://ffmpeg.org/][ffmpeg]]

ffmpeg is only used to convert video files.

Then a scheme compiler is needed to run the script. I'm using [[https://www.gnu.org/software/guile/][guile]]
and I didn't test it with others.

* Usage

You need a folder with images. Then

#+begin_src shell
$ mkdir mygallery && cd mygallery
$ sig make-all -in /path/to/images
$ firefox index.html
#+end_src

The =make-all= commands creates the gallery given a folder with
images. More commands are shown below.

# -- generated doc
** create

Creates a new gallery outline.

Creates a new gallery outline in the directory specified by the first
argument. If omitted, the current directory is used. The folders
'images', 'thumbnails' and 'resources' are created. The 'resources'
folder is populated with javascript and css files.

The gallery can then be created using 'sig make-all'.

** help

Displays some help text.

** make-all

Creates the gallery by processing given images.

- =--name gallery-name (-n)= the title of the html file
- =--thumbsize size (-t)= the thumbnail size (default is 150)
- =--size size (-s)= the image size (default is 1200)
- =--in dir (-i)= the directory with image files (default is
                           'original')
- =--overwrite (-o)= all existing files are overwritten, default
                           is to only write new files

After image/video files have been processed, the html file is generated.

** make-html

Generates the html file only.

It assumes that image/video files have been processed already and exist
in 'images' and 'thumbnails', respectively.

- =--name gallery-name (-n)= the title of the html file
- =--in dir (-i)= the directory with image files (default is
                           'original')


** version

Display the version and a list of commands.


* Not implemented

- find image files recursively in subdirs
- download button for original image (only if relative path)
- make external commands configurable (to add other switches etc)
- custom css, js files
- custom html snippets before and after the gallery
- custom image title format
- package command (create zip file)

* Credits

This script only composes great work of others:

- [[https://github.com/blueimp/Gallery][Gallery]] and [[https://github.com/blueimp/Bootstrap-Image-Gallery][Bootstrap Image Gallery]] makes the image gallery (html,
  css and javascript)
- [[http://getbootstrap.com][bootstrap]] for styling
- software mentioned above


* License

Copyrighted by me, distributed under GPLv3 or later.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Emacs; see the file COPYING. If not, write to the Free
Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
02110-1301, USA.
